# ファイルパス: configs/models/spiking_hrm.yaml
# (新規作成)
# Title: Spiking-HRMモデル設定
# Description: 脳の情報処理階層を模倣し、異なる時間スケールで未来予測を行う
#              階層的循環記憶（HRM）モデルのアーキテクチャ設定ファイル。

model:
  path: "spiking_hrm_model.pth"
  architecture_type: "spiking_hrm" # 新しいアーキテクチャタイプ
  d_model: 256
  time_steps: 64 # SNNのシミュレーションステップ数

  # HRM固有のパラメータ
  hrm_layers: 3 # 階層数
  layer_dims: [256, 128, 64] # 各階層の次元数 (下位層から順に)
  layer_clocks: [1, 4, 16]   # 各階層の更新頻度 (下位層ほど高頻度)

  neuron:
    type: "lif"
