# matsushibadenki/snn4/configs/base_config.yaml
# プロジェクトの基本設定ファイル

# 共通設定
seed: 42
device: "auto"

# データ設定
data:
  path: "data/sample_data.jsonl"
  format: "simple_text"
  split_ratio: 0.1
  max_vocab_size: 50000
  tokenizer_name: "gpt2"

# 学習パラメータ設定
training:
  paradigm: "physics_informed"
  epochs: 10
  batch_size: 8
  
  meta_cognition:
    enabled: true
    error_threshold: 0.8
    modulation_strength: 0.05

  planner:
    learning_rate: 0.001
    model_path: "runs/planner/best_model.pth"

  gradient_based:
    type: "standard"
    learning_rate: 0.001
    use_scheduler: true
    grad_clip_norm: 1.0
    warmup_epochs: 1
    use_amp: true
    loss:
      ce_weight: 1.0
      spike_reg_weight: 0.001
      sparsity_reg_weight: 0.0
      mem_reg_weight: 0.00001
    distillation:
      teacher_model: "gpt2"
      loss:
        ce_weight: 0.3
        distill_weight: 0.7
        spike_reg_weight: 0.001
        sparsity_reg_weight: 0.0
        mem_reg_weight: 0.00001
        temperature: 2.0

  biologically_plausible:
    learning_rule: "CAUSAL_TRACE" # デフォルトの学習則
    # --- 適応的因果スパース化 ---
    adaptive_causal_sparsification:
      enabled: false
      contribution_threshold: 0.01 # この貢献度以下のシナプスは学習を抑制
    # --- パーティクルフィルタ (確率的アンサンブル) ---
    particle_filter:
      enabled: false
      num_particles: 20 # アンサンブルを構成するモデル（パーティクル）の数
      noise_std: 0.05   # 各パーティクルに加えるノイズの標準偏差
    neuron:
      tau_mem: 10.0
      v_threshold: 1.0
      v_reset: 0.0
      v_rest: 0.0
    stdp:
      tau_trace: 20.0
      learning_rate: 0.005
      a_plus: 1.0
      a_minus: 1.0
    reward_modulated_stdp:
      tau_eligibility: 100.0
      learning_rate: 0.01
    causal_trace:
      tau_eligibility: 150.0
      learning_rate: 0.01

  self_supervised:
    learning_rate: 0.0008
    use_scheduler: true
    grad_clip_norm: 1.0
    warmup_epochs: 1
    use_amp: true
    loss:
      prediction_weight: 1.0
      spike_reg_weight: 0.01
      sparsity_reg_weight: 0.0
      mem_reg_weight: 0.0000001

  physics_informed:
    learning_rate: 0.0005
    use_scheduler: true
    grad_clip_norm: 1.0
    warmup_epochs: 1
    use_amp: true
    loss:
      ce_weight: 1.0
      spike_reg_weight: 0.01
      mem_smoothness_weight: 0.001
  
  probabilistic_ensemble:
    learning_rate: 0.0007
    use_scheduler: true
    grad_clip_norm: 1.0
    warmup_epochs: 1
    use_amp: true
    loss:
      ce_weight: 1.0
      variance_reg_weight: 0.1

  log_dir: "runs/snn_experiment"
  eval_interval: 1
  log_interval: 1
  
# ◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️↓修正開始◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️
model_registry:
  provider: "file"  # "file" or "distributed"
  file:
    path: "runs/model_registry.json"
  redis:
    host: localhost
    port: 6379
    db: 0
# ◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️↑修正終わり◾️◾️◾️◾️◾️◾️◾️◾️◾️◾️

app:
  server_name: "127.0.0.1"
  server_port: 7860
  max_len: 100