# ファイルパス: configs/cifar10_spikingcnn_config.yaml
# (旧: configs/cifar10_hybrid_config.yaml)
# Title: SpikingCNNモデル CIFAR-10用設定
# Description: CIFAR-10データセットでSpikingCNNモデルを訓練・評価するための設定ファイル。
model:
  path: "spiking_cnn_cifar10.pth"
  architecture_type: "spiking_cnn"
  time_steps: 16
  neuron:
    type: "lif"
