# ファイルパス: configs/cifar10_spikingcnn_config.yaml
# コードの最も最初には、ファイルパス、ファイルの内容を示したタイトル、機能の説明を詳細に記述してください。 修正内容は記載する必要はありません。
# Title: SpikingCNNモデル CIFAR-10用設定
# Description: CIFAR-10データセットでSpikingCNNモデルを訓練・評価するための設定ファイル。
# 改善点(v1): time_stepsを増やして精度向上を試みる。
model:
  path: "spiking_cnn_cifar10.pth"
  architecture_type: "spiking_cnn"
  time_steps: 32 # 時間ステップ数を増やす (例: 16 -> 32)
  neuron:
    type: "lif"
